### ISSUE TITLE
Error installing YARD documentation for stuffed_bunny 1.0.2

### ISSUE THREAD

**Issue by jdickey** [customink/stuffed_bunny#5]
```
$ gem install stuffed_bunny
Fetching: stuffed_bunny-1.0.2.gem (100%)
Successfully installed stuffed_bunny-1.0.2
Building YARD (yri) index for stuffed_bunny-1.0.2...
ERROR:  While generating documentation for stuffed_bunny-1.0.2
... MESSAGE:   can't modify frozen String
... YARDOC args: --no-progress -c -n --db /Users/jeffdickey/src/conversagence/discovery/v1/discovery_cs_v1/./gemsets/extras/doc/stuffed_bunny-1.0.2/.yardoc --quiet lib
(continuing with the rest of the installation)
Done installing documentation for stuffed_bunny after 0 seconds
1 gem installed
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
$ gem --version
2.6.8
$ yardoc --version
yard 0.9.5
$
```

Can someone who more clearly understands what's blowing up give me some pointers? Thanks.

I've never seen such a problem installing any other Gem thus far.

**Comment by jdickey** [comment]
Never mind. Sometime during this morning's update to Ruby 2.3.3, my `RUBYOPT` got changed to `-W1 -Itest --enable=frozen-string-literal`.  The last of those three directives is new.  Fixed.

I should probably go see if Yardoc has an issue about the `frozen-string-literal` feature breaking stuff. Très weird. Sorry to bother you folks.

**Comment by chmurph2** [comment]
No worries, thanks for reporting it regardless.  I was just trying to reproduce it and couldn't.

**Comment by jdickey** [comment]
Odd that you couldn't repro; I've spun it up in a Fedora VM as well as my OS X (El Cap) native system. Did you remember to add `--enable=frozen-string-literal` to `RUBYOPT`? I have an old Fedora VM running Ruby 2.2.3 that can reproduce this error as well. Not really *your* problem, but until the Yard folks fix the issue I'm opening now, something you might want to be aware of when producing your own docs.

Thanks again.

**Comment by chmurph2** [comment]
I stopped trying to repro because I saw your follow up comment above. :)  Thanks for the heads up, appreciate it!
