### ISSUE TITLE
What am I missing to get StuffedBunny 1.0.2 working with Bunny 2.6.2?

### ISSUE THREAD

**Issue by jdickey** [customink/stuffed_bunny#6]
I can create a connection to the RabbitMQ server by instantiating `Bunny` when `stuffed_bunny` **is not** included. I cannot do so *with* `stuffed_bunny`. 

Easiest demo is a `pry` session. 

```
$ brew services list | grep rabbitmq # show that the server is running
rabbitmq   started jeffdickey /Users/jeffdickey/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
$ bin/pry
[1] pry(main)> require 'stuffed_bunny'
true
[2] pry(main)> StuffedBunny::VERSION
"1.0.2"
[3] pry(main)> Bunny::VERSION
"2.6.2"
[4] pry(main)> connection = Bunny.new
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /Users/jeffdickey/src/conversagence/util/conversagence-message_queue/gemset/gems/stuffed_bunny-1.0.2/lib/stuffed_bunny/bunny_overrides.rb:20:in `initialize'
[5] pry(main)> reset
Pry reset.
[1] pry(main)> require 'bunny'
true
[2] pry(main)> Bunny::VERSION
"2.6.2"
[3] pry(main)> connection = Bunny.new
#<Bunny::Session:0x7fd138d4afd8 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>
[4] pry(main)> connection.close
:closed
[5] pry(main)> exit
$ rabbitmqctl report | head -32
Reporting server status on {{2016,12,18},{16,59,54}}

 ...
Status of node rabbit@localhost ...
[{pid,28475},
 {running_applications,
     [{rabbitmq_management_visualiser,"RabbitMQ Visualiser","3.6.4"},
      {rabbitmq_management,"RabbitMQ Management Console","3.6.4"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.4"},
      {rabbit,"RabbitMQ","3.6.4"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
      {mnesia,"MNESIA  CXC 138 12","4.14.1"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.4"},
      {webmachine,"webmachine","1.10.3"},
      {mochiweb,"MochiMedia Web Server","2.13.1"},
      {ssl,"Erlang/OTP SSL application","8.0.2"},
      {public_key,"Public key infrastructure","1.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.4"},
      {os_mon,"CPO  CXC 138 46","2.4.1"},
      {sasl,"SASL  CXC 138 11","3.0.1"},
      {inets,"INETS  CXC 138 49","6.3.3"},
      {rabbit_common,[],"3.6.4"},
      {xmerl,"XML parser","1.3.12"},
      {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"},
      {crypto,"CRYPTO","3.7.1"},
      {compiler,"ERTS  CXC 138 10","7.0.2"},
      {syntax_tools,"Syntax tools","2.1"},
      {stdlib,"ERTS  CXC 138 10","3.1"},
      {kernel,"ERTS  CXC 138 10","5.1"}]},
 {os,{unix,darwin}},
 {erlang_version,
     "Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true] [dtrace]\n"},
$
```

**Comment by chmurph2** [comment]
Hi Jeff, I'm sorry you ran into trouble and I apologize for not getting back to you sooner.  Thank you for opening the issue.

The problem is this gem only supports version of Bunny up to 1.4.1.  I've opened a PR to explicitly enforce that.  More work is needed to support newer versions of Bunny in `stuffed_bunny`.  Here at work, we're sticking with Bunny 1.4.1 for the time being, so I'm not sure when it'll get priority.

**Comment by jdickey** [comment]
Thanks for the reply, and it's great to have StuffedBunny for folks maintaining legacy systems for which the newer releases introduce breaking changes.

However, given that we were using Bunny (and evaluating StuffedBunny) for a new project, and given that we have shop rules (reflecting painful experience) that prohibit introducing dependencies locked to legacy components without an absolutely compelling business case for doing so, we've (reluctantly) set aside StuffedBunny.

As resources become available and our (recently-begun) use of Bunny expands to other projects, we may look at a PR or fork to get StuffedBunny up to current scratch. Even evaluating how difficult that would be is beyond our present abilities; the fact that such an effort has not yet been made (or even recorded as in-progress via [issues](https://github.com/customink/stuffed_bunny/issues) or [PRs](https://github.com/customink/stuffed_bunny/pulls) urges caution.
